services:
  client:
    image: zizutg/multi-client
    restart: always

  api:
    image: zizutg/multi-server
    restart: always
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - PGUSER=${PGUSER}
      - PGHOST=${PGHOST}
      - PGDATABASE=${PGDATABASE}
      - PGPASSWORD=${PGPASSWORD}
      - PGPORT=${PGPORT}

  worker:
    image: zizutg/multi-worker
    restart: always
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}

  nginx:
    image: zizutg/multi-nginx
    restart: always
    depends_on:
      - client
      - api
    ports:
      - "3050:80"
